@AgendaMedica.API_HostAddress = http://localhost:5132

GET {{AgendaMedica.API_HostAddress}}/users/
Accept: application/json

###
GET {{AgendaMedica.API_HostAddress}}/users/1
Accept: application/json

###
POST {{AgendaMedica.API_HostAddress}}/users
Content-Type: application/json

{
  "name": "Fulana",
  "email": "fulana@email.com",
  "password": "12345678",
  "photo": "https://photos.com/myphoto.png",
  "birthDate": "1990-01-01"
}

###
PUT {{AgendaMedica.API_HostAddress}}/users/12
Content-Type: application/json

{
  "name": "Sicrano",
  "email": "sicrano@email.com",
  "password": "12345678",
  "birthDate": "1990-01-01",
  "photo": "https://photos.com/myphoto.png"
}

###
DELETE {{AgendaMedica.API_HostAddress}}/users/1
