@AgendaMedicaAPI_HostAddress = http://localhost:5132

GET {{AgendaMedicaAPI_HostAddress}}/users/
Accept: application/json

###
GET {{AgendaMedicaAPI_HostAddress}}/pacients/
Accept: application/json

###
GET {{AgendaMedicaAPI_HostAddress}}/doctors/
Accept: application/json

###
GET {{AgendaMedicaAPI_HostAddress}}/appointment-times/
Accept: application/json

###
GET {{AgendaMedicaAPI_HostAddress}}/users/1
Accept: application/json

###
GET {{AgendaMedicaAPI_HostAddress}}/pacients/1
Accept: application/json

###
GET {{AgendaMedicaAPI_HostAddress}}/doctors/1
Accept: application/json

###
POST {{AgendaMedicaAPI_HostAddress}}/users
Content-Type: application/json

{
  "name": "Fulana",
  "email": "fulana@email.com",
  "password": "12345678",
  "photo": "https://photos.com/myphoto.png",
  "birthDate": "1990-01-01"
}

###
POST {{AgendaMedicaAPI_HostAddress}}/pacients
Content-Type: application/json

{
  "name": "Fulano",
  "email": "fulano@email.com",
  "password": "12345678",
  "photo": "https://photos.com/myphoto.png",
  "birthDate": "1990-01-01"
}

###
POST {{AgendaMedicaAPI_HostAddress}}/appointment-times/
Content-Type: application/json

{
  "startTime": "2025-05-26T13:00:00Z",
  "doctorId": 2
}

###
PUT {{AgendaMedicaAPI_HostAddress}}/users/1
Content-Type: application/json

{
  "name": "Sicrano",
  "email": "sicrano@email.com",
  "password": "12345678",
  "birthDate": "1990-01-01",
  "photo": "https://photos.com/myphoto.png"
}

###
POST {{AgendaMedicaAPI_HostAddress}}/appointment-times/
Content-Type: application/json

{
  "startTime": "2025-05-26T13:00:00Z",
  "doctorId": 2
}
###
DELETE {{AgendaMedicaAPI_HostAddress}}/users/1

###
DELETE {{AgendaMedicaAPI_HostAddress}}/appointment-times/1
